### ISSUE TITLE
RA MCV Cashes on Linux Distro

### ISSUE THREAD

**Issue by SteamsDev** [Zeruel87/Cameo-mod#34]
Not sure if this is a known issue but I thought I'd bring it up anyway. RA MCV seems to always crash for me whenever I'm on Linux. Any other MCV seems to be fine...

Attached the debug log to hopefully help make things easier.

[exception-2020-12-16T231053Z.log](https://github.com/Zeruel87/Cameo-mod/files/5706751/exception-2020-12-16T231053Z.log)

**Comment by tjk-ws** [comment]
https://github.com/Zeruel87/Cameo-mod/pull/35 should fix this, does it still happen?

**Comment by SteamsDev** [comment]
It did. My version was simply outdated. Thanks though for your help!
