### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Nitay108** [Zeruel87/Cameo-mod#54]
Whenever I add AI called X_Monsters it crashes the game instantly or after a while(30-15sec).

**Comment by hunterczech** [comment]
What does the crash say? Please before you post a bug report include a crash log. 

1) Windows+R
2) %appdata%\OpenRA\logs
3) exception-####-##-########.log where # is date and ID of crash.
Drag and drop to attach files here.

Thanks!

**Comment by hunterczech** [comment]
Found and fixes the issue. I however don't have repo of 0.22, so if you want u can download and apply the fine manually, or wait for somebody else to PR it.
[mods.zip](https://github.com/Zeruel87/Cameo-mod/files/6780087/mods.zip)

**Comment by Nitay108** [comment]
Thank's I try it out, allso should I close issue on github or provide crash report as requested?

 
 

Sent: Wednesday, July 07, 2021 at 10:09 PM

**Comment by hunterczech** [comment]
If that fix works for you then you can close the issue.
